name: Build COVESA emulators

on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: [self-hosted, high-performance-ubuntu]
    steps:
      - name: Set-up environment
        run: |
          REPOSITORY_ROOT=$(dirname "$GITHUB_WORKSPACE")
          GITHUB_ACTIONS_ROOT=$(dirname "$REPOSITORY_ROOT")
          AOSP_ROOT=$GITHUB_ACTIONS_ROOT/$GITHUB_REF_NAME
          VSS_ROOT=$GITHUB_ACTIONS_ROOT/vehicle_signal_specification
          VSS_TOOLS_ROOT=$GITHUB_ACTIONS_ROOT/vss-tools
          echo "AOSP_ROOT=$AOSP_ROOT" >> $GITHUB_ENV
          echo "DIST_ROOT=/mnt/emulators" >> $GITHUB_ENV
          echo "VSS_ROOT=$VSS_ROOT" >> $GITHUB_ENV
          echo "VSS_TOOLS_ROOT=$VSS_TOOLS_ROOT" >> $GITHUB_ENV
      - name: Apply easywsclient patch to socket-based VHAL
        run: |
          git -C "$AOSP_ROOT/device/generic/car/emulator/vhal_sockets_vehicle_hardware/external/easywsclient" \
            apply --check --reverse "$AOSP_ROOT/device/generic/car/emulator/vhal_sockets_vehicle_hardware/external/easywsclient_fix.patch" \
          || git -C "$AOSP_ROOT/device/generic/car/emulator/vhal_sockets_vehicle_hardware/external/easywsclient" \
             apply "$AOSP_ROOT/device/generic/car/emulator/vhal_sockets_vehicle_hardware/external/easywsclient_fix.patch"
      - name: Generate VSS based VHAL
        run: |
          source "$VSS_TOOLS_ROOT/.venv/bin/activate"
          vspec export vhal --no-extend-new --aosp-workspace-path "$AOSP_ROOT" --vspec "$VSS_ROOT/spec/VehicleSignalSpecification.vspec"
      - name: Approve AIDL changes
        run: |
          cd "$AOSP_ROOT"
          source build/envsetup.sh
          lunch sdk_car_arm64-trunk_staging-userdebug
          m android.car-module.stubs.source-update-current-api \
            android.car-stubs-docs-update-current-api \
            vendor.android.hardware.automotive.vehicle.property-update-api
      - name: Generating annotation enums (post processing)
        run: |
          cd "$AOSP_ROOT"
          source build/envsetup.sh
          lunch sdk_car_arm64-trunk_staging-userdebug
          source "$VSS_TOOLS_ROOT/.venv/bin/activate"
          python "hardware/interfaces/automotive/vehicle/tools/generate_annotation_enums.py"
          git --git-dir="hardware/interfaces/.git" --work-tree="hardware/interfaces" restore \
            "automotive/vehicle/aidl/generated_lib/4/java/AccessForVehicleProperty.java" \
            "automotive/vehicle/aidl/generated_lib/4/java/ChangeModeForVehicleProperty.java"
      - name: VehiclePropertyIdsParser (post processing)
        run: |
          java -jar "$AOSP_ROOT/packages/services/Car/tools/vehiclepropertyidsparser/prebuilt/VehiclePropertyIdsParser.jar" \
            "$AOSP_ROOT/packages/services/Car/car-lib/src" \
            "$AOSP_ROOT/vendor/car/packages/services/Car/car-lib/src" \
            "$AOSP_ROOT/packages/services/Car/car-lib/generated-prop-config/CarSvcProps.json"
      - name: Build ARM emulator image
        run: |
          cd "$AOSP_ROOT"
          source build/envsetup.sh
          lunch sdk_car_arm64-trunk_staging-userdebug
          m emu_img_zip
      - name: Build x86_64 emulator image
        run: |
          cd "$AOSP_ROOT"
          source build/envsetup.sh
          lunch sdk_car_x86_64-trunk_staging-userdebug
          m emu_img_zip
      - name: Build Android Car Library
        run: |
          cd "$AOSP_ROOT"
          source build/envsetup.sh
          lunch sdk_car_x86_64-trunk_staging-userdebug
          m android.car
