name: Checkout AOSP

on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: [self-hosted, high-performance-ubuntu]
    steps:
      - name: repo init if workspace is empty
        run: |
          repo version
          REPOSITORY_ROOT=$(dirname "$GITHUB_WORKSPACE")
          GITHUB_ACTIONS_ROOT=$(dirname "$REPOSITORY_ROOT")
          AOSP_ROOT=$GITHUB_ACTIONS_ROOT/$GITHUB_REF_NAME
          echo "AOSP_ROOT=$AOSP_ROOT" >> $GITHUB_ENV
          mkdir -p "$AOSP_ROOT"
          if [ -z "$(ls -A $AOSP_ROOT)" ]; then
            cd "$AOSP_ROOT"
            repo init -u "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" -b "$GITHUB_REF_NAME" --depth=1
          else
            echo "Directory is not empty, skipping repo init"
          fi
        # print all lines from the script and stop on errors
        shell: bash -ex {0}
      - name: repo sync
        run: |
          cd "$AOSP_ROOT"
          repo sync -c
