name: Checkout AOSP

on:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: [self-hosted, high-performance-ubuntu]
    steps:
      - name: repo init if workspace is empty
        run: |
          repo version
          REPOSITORY_ROOT=$(dirname "$GITHUB_WORKSPACE")
          GITHUB_ACTIONS_ROOT=$(dirname "$REPOSITORY_ROOT")
          export AOSP_ROOT="$GITHUB_ACTIONS_ROOT/$GITHUB_REF_NAME"
          if [[ ! -d "$AOSP_ROOT" || -z "$(ls -A '${AOSP_ROOT}'" ]]; then
            mkdir -p "$AOSP_ROOT"
            cd "$AOSP_ROOT"
            repo init -u $GITHUB_SERVER_URL/$GITHUB_REPOSITORY -b $GITHUB_REF_NAME --depth=1
          else
            exit 1
          fi
        # print all lines from the script
        shell: bash -x {0}
